services:
  frontend:
    build:
      context: ./frontend
    container_name: lori-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/usr/app/src
      # - ./frontend/public:/usr/src/app/public:rw,z
      # - ./frontend/package.json:/usr/src/app/package.json:rw,z
    environment:
      - backendip="http://localhost:5000/"
      - IONIC_ENABLE_LIVE_RELOAD=true

  backend:
    build:
      context: ./backend
    container_name: lori-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/:/usr/src/app/:rw,z
    environment:
      - FLASK_ENV=development
  
  db:
    image: postgres:latest
    container_name: lori-database
    environment:
      POSTGRES_USER: loris
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: lori_database
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
