services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/usr/app/src
      # - ./frontend/public:/usr/src/app/public:rw,z
      # - ./frontend/package.json:/usr/src/app/package.json:rw,z
    environment:
      - backendip="http://localhost:5000/"
      - IONIC_ENABLE_LIVE_RELOAD=true

  backend:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: backend
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./database:/pb_data 
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5